fix: fix way to make action fail

diff --git a/.github/actions/check-repository-includes-package/action.yml b/.github/actions/check-repository-includes-package/action.yml
--- a/.github/actions/check-repository-includes-package/action.yml
+++ b/.github/actions/check-repository-includes-package/action.yml
@@ -32,8 +32,10 @@ runs:
         echo "$ACTUAL"
         echo "$EXPECTED"
 
-        [ "$ACTUAL" = "$EXPECTED" ] && exit 0
-        core.setFailed("Package manifest does not match to the one in the repository manifest.")
+        if [ "$ACTUAL" != "$EXPECTED" ]; then
+          echo "::error::Package manifest does not match to the one in the repository manifest."
+          exit 1
+        fi
 
     - run: |
         echo "Validation existence of ${{ env.pkg-name }}:${{ env.pkg-version }}: ok" 
diff --git a/.github/actions/validate-package-manifest/action.yml b/.github/actions/validate-package-manifest/action.yml
--- a/.github/actions/validate-package-manifest/action.yml
+++ b/.github/actions/validate-package-manifest/action.yml
@@ -54,22 +54,34 @@ runs:
         echo "expected-url=$EXPECTED_URL" >> $GITHUB_ENV
 
     - if: ${{ env.pkg-name-type != 'string' }}
-      run: core.setFailed('"name" must be string, not ${{ env.pkg-name-type }}')
+      run: |
+        echo '::error::"name" must be string, not ${{ env.pkg-name-type }}'
+        exit 1
 
     - if: ${{ env.pkg-display-name-type != 'string' }}
-      run: core.setFailed('"displayName" must be string, not ${{ env.pkg-display-name-type }}')
+      run: |
+        echo '::error::"displayName" must be string, not ${{ env.pkg-display-name-type }}'
+        exit 1
 
     - if: ${{ env.pkg-version-type != 'string' }}
-      run: core.setFailed('"version" must be string, not ${{ env.pkg-version-type }}')
+      run: |
+        echo '::error::"version" must be string, not ${{ env.pkg-version-type }}'
+        exit 1
 
     - if: ${{ env.pkg-url-type != 'string' }}
-      run: core.setFailed('"url" must be string, not ${{ env.pkg-url-type }}')
+      run: |
+        echo '::error::"url" must be string, not ${{ env.pkg-url-type }}'
+        exit 1
 
     - if: ${{ env.pkg-author-name-type != 'string' }}
-      run: core.setFailed('"author.name" must be string, not ${{ env.pkg-author-name-type }}')
+      run: |
+        echo '::error::"author.name" must be string, not ${{ env.pkg-author-name-type }}'
+        exit 1
 
     - if: ${{ env.pkg-author-email-type != 'string' }}
-      run: core.setFailed('"author.email" must be string, not ${{ env.pkg-author-email-type }}')
+      run: |
+        echo '::error::"author.email" must be string, not ${{ env.pkg-author-email-type }}'
+        exit 1
           
     - name: Check version
       id: version-check
@@ -89,12 +101,14 @@ runs:
     - name: Version check failed
       if: ${{ always() && steps.version-check.outputs.failed }}
       run: |
-        core.setFailed("Manifest version incorrect: expected ${{ env.expected-version }} but got ${{ env.pkg-version }}")
+        echo "::error::Manifest version incorrect: expected ${{ env.expected-version }} but got ${{ env.pkg-version }}"
+        exit 1
 
     - name: URL check failed
       if: ${{ always() && steps.url-check.outputs.failed }}
       run: |
-        core.setFailed("Manifest URL incorrect: expected ${{ env.expected-url }} but got ${{ env.pkg-url }}")
+        echo "::error::Manifest URL incorrect: expected ${{ env.expected-url }} but got ${{ env.pkg-url }}"
+        exit 1
 
     - run: |
         echo "Validation ${{ env.manifest-file }}: ok" 
diff --git a/.github/actions/validate-repository-manifest/action.yml b/.github/actions/validate-repository-manifest/action.yml
--- a/.github/actions/validate-repository-manifest/action.yml
+++ b/.github/actions/validate-repository-manifest/action.yml
@@ -28,24 +28,33 @@ runs:
         echo "packages-type=$PACKAGES_TYPE" >> $GITHUB_ENV
 
     - if: ${{ env.name-type != 'string' }}
-      run: core.setFailed('"name" must be string, not ${{ env.name-type }}')
+      run: |
+        echo '::error::"name" must be string, not ${{ env.name-type }}'
+        exit 1
 
     - if: ${{ env.author-type != 'string' }}
-      run: core.setFailed('"author" must be string, not ${{ env.author-type }}')
+      run: |
+        echo '::error::"author" must be string, not ${{ env.author-type }}'
+        exit 1
 
     - if: ${{ env.id-type != 'string' }}
-      run: core.setFailed('"id" must be string, not ${{ env.id-type }}')
+      run: |
+        echo '::error::"id" must be string, not ${{ env.id-type }}'
+        exit 1
 
     - if: ${{ env.url-type != 'string' }}
-      run: core.setFailed('"url" must be string, not ${{ env.url-type }}')
+      run: |
+        echo '::error::"url" must be string, not ${{ env.url-type }}'
+        exit 1
 
     - if: ${{ env.packages-type != 'object' }}
-      run: core.setFailed('"packages" must be object, not ${{ env.packages-type }}')
+      run: |
+        echo '::error::"packages" must be object, not ${{ env.packages-type }}'
+        exit 1
 
     - name: Check package manifests
       run: |
         MANIFEST="$(cat ${{ inputs.filename }} | jq -cM ".")"
-        ERROR="::error file=${{ inputs.filename }}"
         FAILED=0
 
         # iterate over ".packages" object
@@ -55,7 +64,7 @@ runs:
             PKGSET_TYPE="$(echo "$MANIFEST" | jq -r "$PKGSET_QUERY | type")"
 
             if [ "$PKGSET_TYPE" != "object" ]; then
-                echo "$ERROR::package listing $PKG_NAME must be object, not $PKGSET_TYPE"
+        echo "::error::package listing $PKG_NAME must be object, not $PKGSET_TYPE"
                 FAILED=1
             fi
 
@@ -74,27 +83,27 @@ runs:
                 PKG_AUTHOR_EMAIL_TYPE="$(echo "$PKG_MANIFEST" | jq -r ".author.email | type")"
 
                 if [ "$PKG_NAME_INNER" != "$PKG_NAME" ]; then
-                    echo "$ERROR::package name mismatch in $PKG_NAME@$PKG_VERSION"
+                    echo "::error::package name mismatch in $PKG_NAME@$PKG_VERSION"
                     FAILED=1
                 fi
                 if [ "$PKG_DISPLAY_NAME_TYPE" != "string" ]; then
-                    echo "$ERROR::package displayName must be string, not $PKG_DISPLAY_NAME_TYPE in $PKG_NAME@$PKG_VERSION"
+                    echo "::error::package displayName must be string, not $PKG_DISPLAY_NAME_TYPE in $PKG_NAME@$PKG_VERSION"
                     FAILED=1
                 fi
                 if [ "$PKG_VERSION_INNER" != "$PKG_VERSION" ]; then
-                    echo "$ERROR::package version mismatch in $PKG_NAME@$PKG_VERSION"
+                    echo "::error::package version mismatch in $PKG_NAME@$PKG_VERSION"
                     FAILED=1
                 fi
                 if [ "$PKG_URL_TYPE" != "string" ]; then
-                    echo "$ERROR::package url must be string, not $PKG_URL_TYPE in $PKG_NAME@$PKG_VERSION"
+                    echo "::error::package url must be string, not $PKG_URL_TYPE in $PKG_NAME@$PKG_VERSION"
                     FAILED=1
                 fi
                 if [ "$PKG_AUTHOR_NAME_TYPE" != "string" ]; then
-                    echo "$ERROR::package author name must be string, not $PKG_AUTHOR_NAME_TYPE in $PKG_NAME@$PKG_VERSION"
+                    echo "::error::package author name must be string, not $PKG_AUTHOR_NAME_TYPE in $PKG_NAME@$PKG_VERSION"
                     FAILED=1
                 fi
                 if [ "$PKG_AUTHOR_EMAIL_TYPE" != "string" ]; then
-                    echo "$ERROR::package author email must be string, not $PKG_AUTHOR_EMAIL_TYPE in $PKG_NAME@$PKG_VERSION"
+                    echo "::error::package author email must be string, not $PKG_AUTHOR_EMAIL_TYPE in $PKG_NAME@$PKG_VERSION"
                     FAILED=1
                 fi
             done
